name = "bybit-smart-bot"

main = "worker.js"

compatibility_date = "2026-06-21"

[[d1_databases]]
binding = "DB"
database_name = "bybitbot"
database_id = "PUT_YOUR_D1_ID_HERE"

[triggers]
crons = ["*/5 * * * *"]